name: mobilt_java23_ardi_fetiu_flutter_v_2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.1.0 # Added for saving data

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.9.2 # Ensure compatibility with the latest Flutter

flutter_icons:
  android: true
  image_path: "assets/images/logo.png" # Path to your app icon

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png # Add your local resources here
